### ISSUE TITLE
ConnectionRefusedError for xdg-open on Ubuntu 20.04

### ISSUE THREAD

**Issue by sitnarf** [CamielBouchier/cb_thunderlink#11]
The button is working, but xdg-open does not works for both cb and original links.

```
  xdg-open cbthunderlink://MjAxOS0wOS0wMlQwODozODoyMy4wMDBaO2lNb2JpbHkuZXUgPGluZm9AaW1vYmlseS5ldT4=
  File "cb_thunderlink.py", line 202, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
[1277893] Failed to execute script cb_thunderlink

```

**Additional information:**
- Thunderbird 78.4.0 installed with snap
- cb_thunderlink 0.6

**Comment by RadoslawKokoc** [comment]
I have very similar problem but with cb_thunderlink.exe. 
`C:\thunderlink\cb_thunderlink>C:\thunderlink\cb_thunderlink\cb_thunderlink.exe "thunderlink://messageid=ee0c03d5162447cbb035c93ebdc8c422@Ex2.example.pl"
Traceback (most recent call last):
  File "cb_thunderlink.py", line 202, in <module>
ConnectionRefusedError: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia
[11616] Failed to execute script cb_thunderlink`

I'm using
- Thunderbird 78.4.3;
- cb_thunderlink 0.6.

**Comment by CamielBouchier** [comment]
@sitnarf ,

The issue is related to the `snap` install of thunderbird and the sandboxing that comes with it.
It will work with a normal `apt-get` install.

There seems to be quite some references to issues with `native-messaging` under `snap`. 

I won't work on it, unless someone has a proof of concept working of `native-messaging` with `snap`. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging for what should be working.

Camiel B.

**Comment by sitnarf** [comment]
@CamielBouchier Thanks for the information.
