### ISSUE TITLE
Clarify upgrade steps

### ISSUE THREAD

**Issue by vlcinsky** [CamielBouchier/cb_thunderlink#17]
Make clear, what steps are needed to upgrade the plugin.
This probably applies only to system integration, but even few words would help.

Try to clarify:
- is there any need to remove/deregister the previous version? How?
- how to test, the integration works

Thanks for great plugin. It is hard to imagine to work without that.

**Comment by CamielBouchier** [comment]
Low priority ...

But maybe you can help? Let me just describe very briefly how things work, then you can for sure derive ...

* Thunderbird loads the `xpi` from a location `foobar`.
* Thunderbird starts `foobar\cb_thunderlink` - let me call it Process1 - through native messaging (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)
* In order native messaging to work, a connector file is needed on a location as described in above link. That file is written by `foobar\cb_thunderlink register`.
* The Process1 just sits there and listens to incoming connections.
* An incoming connection to Process1 is generated by again starting `foobar\cb_thunderlink` - let me call it Process 2. In order to have links working your OS need to know it it needs to start `foobar\cb_thunderlink SomeArgument` when a link is clicked. That is registered in the registry (Windows) or through gio under Linux. Again `foobar\cb_thunderlink register` takes care of that.

So just get your head around the fact that cb_thunderlink has 3 different functionalities, according to the arguments it is called with:
- The "background" process P1, that is just sitting there and listening to incoming commands (that then are piped through to thunderbird)
- The process P2 that is started when a link is clicked, sends the command to P1 and quits.
- A process that creates the glue-files and does the registrations when called with the register argument.

Camiel B

**Comment by CamielBouchier** [comment]
See [architecture](https://camiel.bouchier.be/en/cb_thunderlink/architecture) and [checklist](https://camiel.bouchier.be/en/cb_thunderlink/checklist). Should answer a lot. If not, we can extend step by step.

Camiel B.
