### ISSUE TITLE
Please do elaborate on your assumption that TB drops ability to open emails via message-ids 

### ISSUE THREAD

**Issue by novoid** [CamielBouchier/cb_thunderlink#28]
Hi,

I read on https://camiel.bouchier.be/en/cb_thunderlink that you think that "there is a remote risk that searching on the message-id gets lost in the further future reduction of Thunderbird API".

What is the advantage of switching to a combination of email date + author?

In my head, there is a red alarm when you describe a process of switching from the standard of identifying emails (message-IDs) to a non-standard identification method instead. Any decent mail client offers retrieval possibilities based on message-IDs.

I once had a setup where I could open a link to an email within my notes either within notmuch or within Thunderbird. Both were able to identify the same email within their systems using the message IDs. Although I do not use notmuch any more, this was a comforting situation since I knew that there is this level of freedom waiting, just in case.

Message-IDs ought to be worldwide unique. Therefore, they can be used to communicate to tech-savvy peers like "please refer to $MESSAGEID in case you want to find out more about this issue". This new date/author method is most likely only of any use within cb_thunderlink.

What are your thoughts on these questions?

_Thanks a LOT for providing cb_thunderlink! I just discovered it and it saves hundreds or even thousands of email links within my personal notes (Org mode)._

**Comment by CamielBouchier** [comment]
Hi,

I don't like either ... 
And currently I still do rely on the classic `thunderlink://message-id=..` as well.
(especially because I have a proof-of-concept convertor in the drawer if I ever would be forced to `cbthunderink://`)

I do see that thunderbird API is moving away from its traditional API to `webextensions` API.
(by the way, that's why you will find now zillions of plugins that are not available anymore)

Currently the `message-id` still can be searched for through the traditional API that they partly leave available.
The `webextensions` currently *still* does not allow to search on `message-id`. 
It does however allow to search on `author` and `date`. And that's why I have chosen it as a fallback.

You might be inerested in
https://thunderbird-webextensions.readthedocs.io/en/78/messages.html# and
https://thunderbird-webextensions.readthedocs.io/en/78/messages.html#query-queryinfo

Hope this helps.

Camiel B.

**Comment by novoid** [comment]
Thank you!
