### ISSUE TITLE
integration with org-mode

### ISSUE THREAD

**Issue by gour** [CamielBouchier/cb_thunderlink#30]
Hello,

new Thunderbird user here just migrated from Claws-mail and curious if `cb_thunderlink` can serve the same purpose as the one described [here](https://vxlabs.com/2019/04/20/link-thunderbird-emails-from-emacs-orgmode/) ?

**Comment by CamielBouchier** [comment]
Hi,

I am not fully sure what the question is. 
But if it can be used with org-mode? Yes! We have an org-mode afficionado (See @novoid at #29) here who is running it in org-mode.

Just don't forget:

- You will have to call `cb_thunderlink`-script/program rather than `thunderbird.exe`
- You will have to convert `message://` to `thunderlink://` or `cb_thunderlink://`. Either in emacs, either in an intermediate script, that should be a pretty trivial task.

Camiel B.

**Comment by novoid** [comment]
Hi @gour ,

You can find [my setup on GitHub](https://github.com/novoid/dot-emacs/blob/master/config.org) which is already moved to TB v78.x.
I'm using a custom link like `[[messageid:THEMESSAGEID][ISOTIME SENDER: SUBJECT]]` and I'm pretty happy. Thinking of throwing in an additional `[[cbthunderlink:CBLINK][cb]]` to be on the safe side.

**Comment by gour** [comment]
> Just don't forget:
> 
>     * You will have to call `cb_thunderlink`-script/program rather than `thunderbird.exe`
> 
>     * You will have to convert `message://` to `thunderlink://` or `cb_thunderlink://`. Either in emacs, either in an intermediate script, that should be a pretty trivial task.

Consider that I was also using [Taskwarrior](https://taskwarrior.org/) I bet that this extension could be made to work with it as well?

**Comment by CamielBouchier** [comment]
Again, no idea what Taskwarrior is. But see the [architecture page](https://camiel.bouchier.be/en/cb_thunderlink/architecture). As long as you are triggering the `cb_thunderlink` script/program with the right parameters (i.e. the `thunderlink://` or `cbthunderlink://` you should be good.

Camiel B.
