### ISSUE TITLE
Thunderbird 78.8.1?

### ISSUE THREAD

**Issue by nomatica** [CamielBouchier/cb_thunderlink#31]
When I attempt to load the from the thunderbird  add on library online it says the following:
![image](https://user-images.githubusercontent.com/49659723/111509983-ae21fc00-8723-11eb-9c7a-f9a99704769b.png)

**Comment by CamielBouchier** [comment]
Hey @nomatica ,

That is not my `cb_thunderlink` that replaces the original add-on (and that doesn't work anymore indeed since  thunderbird 68 or so). For installing my `cb_thunderlink` please head to [my site](https://camiel.bouchier.be/en/cb_thunderlink/installation) and follow the instructions.

Camiel B.

**Comment by nomatica** [comment]
thank you.
