### ISSUE TITLE
 Add LICENSE Or COPYING File

### ISSUE THREAD

**Issue by Francewhoa** [CamielBouchier/cb_thunderlink#35]
Hello @CamielBouchier & all other contributors to cb_thunderlink :)

Thanks for keeping alive [ThunderLink](https://addons.thunderbird.net/en-CA/thunderbird/addon/thunderlink/) with your CB_ThunderLink for thunderbird. Appreciated.

I searched for cb_thunderlink license. But found no answer. As of today December 20th, within the GitHub repository the link presently reads `$BeginLicense$` at https://github.com/CamielBouchier/cb_thunderlink/blob/main/cb_put_licenses_on_files.py

For the previous @mikehardy chose this [MPL-2.0 License](https://github.com/mikehardy/thunderlink/blob/master/LICENSE). But for your cb_thunderlink feel really free to choose any license to your liking.

To potentially attract more contributors, more donations, and for a stronger security & privacy, I suggest adding a **LICENSE** file to [this repository](https://github.com/CamielBouchier/cb_thunderlink)

If you're not familiar with a license file, the following free tools might be useful to easily & quickly choose one, then create the license file

* https://choosealicense.com

* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Feel really free to choose any type of license to your liking. If not sure about which type of license file to choose, I suggest this [GNU GPL 3](https://choosealicense.com/licenses/gpl-3.0/). So that you are protected from Liability or Warranty claims. While at the same time, as primary author, you remain fully free to edit your code in any ways to your liking, within the GPL3. Another benefit with GPL3 is that you would remain fully free from external interferences. 

Any volunteers to create a license file? If needed, I would be happy to contribute testing.

**Comment by CamielBouchier** [comment]
Hi,

Struggling with this. I need to give this some further thought.
Actually, it is now "All rights reserved" licensed (should be visible in 
the sources).
Let me also share why:

In the past I was a big supporter of open source software. However I am 
the alter ego of someone who started a quite relevant open source 
project 10 years ago. Some contributors - with much more time than I 
have - entered and grew my gem in a direction that was not exactly what 
I got in mind, which is in its own still fine. However, as I 
anticipated, after 2 years they left the project on its own. It became 
unsupported, unsupportable by me, and in a shape I didn't like. Couple 
of months later it was virtually dead and out of all the major 
distributions. Since then I am struggling more with the open source 
concept, particularly for the aspect "control" and "reputation".

I would be fine with a license where
(i) Copyright is maintained (but that actually goes without saying in 
any license)
(ii) Used in any project, as long it is not functionality that is 
substantially the same as cb_thunderlink (on which I want to keep control)
Open sourcing it under one of the classic FOSS licenses would not 
guarantee (ii), and that's what I am struggling with.

Kind regards,

Camiel B.


------------------------------------------------------------------------
*From:* Francois Carpentier ***@***.***
*Sent:* Monday, December 20, 2021, 10:20 AM
*To:* CamielBouchier/cb_thunderlink
*Cc:* Camiel B; Mention
*Subject:* [CamielBouchier/cb_thunderlink] Add LICENSE File (Issue #35)

**Comment by mikehardy** [comment]
Very interesting point control / reputation. I suppose, in a sense, that there is a test case in thunderlink right now. What I mean specifically is that from a reputation perspective *I* am "thunderlink", and you are cb_thunderlink, so my reputation (or lack of! thunderlink is effectively dead) is my concern as you are a fork / derivative and in control of reputation around cb_thunderlink

so long as you gate contributions to be only what you will specifically support (and it's your github, so you can...) then you may address ii via personal control I think? Others simply can't publish, so no reputation danger, make them fork if you wouldn't support whatever the change is ?

Either way, just in case it's useful - to avoid any doubt for whatever code I might be considered to hold copyright - I would agree to relicense to whatever seems best to whomever is *actually doing the work*. Because the work - keeping code alive - is what has the value to me.

**Comment by CamielBouchier** [comment]
Hi,

Very valid points indeed. I guess in this case the 'handover' was done 
in full mutual consent and completely transparent. It after all being no 
rocket science, neither weighing tons of codelines, I am inclined 
towards just keep using MPL 2.0. In any case, I only have time for a new 
release on Thursday or Friday, which leaves me still some pondering time ;)

Camiel B.

------------------------------------------------------------------------
*From:* Mike Hardy ***@***.***
*Sent:* Monday, December 20, 2021, 4:59 PM
*To:* CamielBouchier/cb_thunderlink
*Cc:* Camiel B; Mention
*Subject:* [CamielBouchier/cb_thunderlink] Add LICENSE Or COPYING File 
(Issue #35)

**Comment by Francewhoa** [comment]
Thanks @CamielBouchier and @mikehardy for your replies

@CamielBouchier :) To facilitate your decision, another free tool you might be interested is https://opensource.org/licenses/category

**Comment by Francewhoa** [comment]
@CamielBouchier :) Like a said above, feel really free to use any license to your liking

About GPL 3. If you're interested, to potentially increase your income. With GPL 3, you would be remaining in FULL control of what your product become in the future years from now and FOREVER. As long as you keep a GPL 3 or equivalent. In other words, fully free from external interference. As you know, with GPL you would be remaining protected from costly lawsuits. In comparison, with an "All rights reserved" you would expose yourself to this risk. Usually, with a "All rights reserved" licence, whom ever as the more money win, and you lose control of your product to their benefit and to the cost of your reputation. If you own a large company with a multimillion dollar team of layers, this is not a concern, but if you don't, this is a risk to consider. In comparison, with GPL your protected. Those lawyers with Evil behaviors, who are serving money above people and above the law, are completely powerless againt a GPL 3. The additional benefit with GPL 3 is that you would automatically and easily get free publicity & potentially increase YOUR income & YOUR traffic to YOUR digital products. For exemple at https://camiel.bouchier.be/en/cb_thunderlink or anywhere else to your liking :)

## Additional benefit with GPL 3:

* **Free Publicity & Increase Your Income & Traffic**
With GPL 3, anybody who uses any part of your code is required to publicly attribute it to you. By including both a copy of YOUR "COPYING" license file and YOUR "COPYRIGHT" file as is with their material. The tip to easily and quickly potential increase your income is to somehow include to add to both your "COPYING" & "COPYRIGHT" files your contact information. So that a future client or donor interested in your services or product is able to easily identify you and find your public contact information. Such as, but not limited to, your primary domain name https://YourProduct.org or https://YourProduct.org plus somehow add your public contact information in text. In turn, whom ever use your code, are required by GPL 3 to add a copy of both your "COPYING" and "COPYRIGHT" license files to their material and their license file. In turn, the  next person has to the same. As you can see, this goes on exponentially. This means that the more people use your code, the more free publicity you get. In turn, the more you can potentially increase your income $. 

In comparison, MPL license has loop wholes. In summary, MPL does not require the other people to include a copy as is of your license "COPYING" and "COPYRIGHT" file AS IS with their materials. To do so, they could include a similar license but not YOUR license files.  In turn, your contact information is stripped or partly stipped. Or they just include the change they made without including your license file as is. In turn, it's much harder for others potential donors or buyer to find you.

Source comparison https://choosealicense.com/licenses/

**Comment by CamielBouchier** [comment]
Hi,
Landed on the pre-existing "Mozilla Public License Version 2.0".
Camiel B.
